# Generated by Django 4.2 on 2024-05-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default='nombre servicio', max_length=200),
        ),
    ]
